In [1]:
import numpy as np

In [23]:
arr = np.ones((2, 2), dtype=np.int16)

In [24]:
arr.flags['C_CONTIGUOUS'] # True

True

In [25]:
e = np.empty((2, 2), dtype=np.float64)
print(e.shape)

(2, 2)


In [27]:
z =np.zeros((2, 2), dtype=np.int32)
print(z)

[[0 0]
 [0 0]]


In [17]:
new_array = np.zeros((2, 2), dtype=np.float64)

In [18]:
new_array = np.array((2, 2), dtype=np.float64)

In [19]:
new_array.shape

(2,)

In [20]:
new_array.fill(0)
new_array

array([0., 0.])

In [35]:
# reshape, ravel and flatten-> multi to single
a = np.arange(1,7)
b = a.reshape((2, -1))

v = b.ravel() 
v[0] = 99
print(b[0, 0])

c= b.flatten()
c[0] = 0 
print(b[0, 0])
#c vs fortran order

c_arr = np.ones((2,3), order='C')
c_arr.strides
c_arr.flags['C_CONTIGUOUS'] # True

f_arr = np.ones((2,3), order='F')
f_arr.strides
f_arr.flags['F_CONTIGUOUS'] # True
# repeating elements : repeat vs tile

arr = np.array([1, 2])
np.repeat(arr, 3) 
np.tile(arr, 3)

99
99


array([1, 2, 1, 2, 1, 2])

In [ ]:
# fancy indexing: take and put
arr = np.array([10, 20, 30, 40, 50])
arr.take([0,2])
print(arr)

arr1 = np.zeros(4)
arr.put([1,2],[3,4])
print(arr1)

#ufunc Methods: .add.reduce and .add.accumulate
a = np.array([1, 2, 3, 4])
np.add.reduce(a)  # 1+2+3+4

np.add.accumulate(a)  # [1, 3, 6, 10]

#trailing 
a = np.ones((4, 3))
b = np.array([1, 2, 3])
(a+b).shape

x = np.arange(4)[:, np.newaxis]
(x + b).shape

v =np.broadcast_to(b,(4, 3))
print(v.strides)

[10 20 30 40 50]
[0. 0. 0. 0.]
(0, 8)


In [46]:
#ufunc Methods: .add.reduceat and .add.outer
x = np.array([1,22,3])
np.multiply.outer(x, x)

arr = np.arange(8)
np.add.reduceat(arr, [0,4])
# we can also write new ufunc in python using numpy.frompyfunc // numba


array([ 6, 22])