In [45]:
import numpy as np

In [ ]:
arr = np.array([[1,2,3,4],[4,5,6,7]], dtype = np.int32)
#strides -> tell us(numpy) where a particular element is in memory\n formula = no.of elements * 4, no of elements(in a row)
arr.strides

(16, 4)

In [11]:
new_arr = arr.T
new_arr.strides

(4, 16)

In [12]:
new_arr

array([[1, 4],
       [2, 5],
       [3, 6],
       [4, 7]], dtype=int32)

In [ ]:
new_arr[1,0] = 8
print(new_arr)
print()
print(arr)
#shallow copy(call by refernce)-changes in the same object and # deep copy(call by value)->copy value to a new obj

[[1 4]
 [8 5]
 [3 6]
 [4 7]]

[[1 8 3 4]
 [4 5 6 7]]


In [18]:
#ravel(shaloow copy) vs flatten(copies into a new data obj)

new_arr1 = arr.ravel()
print(new_arr1)

[1 8 3 4 4 5 6 7]


In [ ]:
new_arr1 [1] = 10
print(new_arr1)
print(new_arr)

[ 1 10  3  4  4  5  6  7]
[[ 1  4]
 [10  5]
 [ 3  6]
 [ 4  7]]


In [25]:
new_flatten = arr.flatten()


In [27]:
new_flatten[1] = 12
print(new_flatten)
print(new_arr)

[ 1 12  3  4  4  5  6  7]
[[ 1  4]
 [10  5]
 [ 3  6]
 [ 4  7]]


In [28]:
#->transpose : to rotate image

In [39]:
#c vs Fortarn Order:
arr2 = np.array([[1,2,3],[4,5,6]], dtype = np.int32, order='C')
print(arr.strides)
arr1 = np.array([[1,2,3],[4,5,6]],dtype=np.int32, order='F')
print(arr1.strides)

(12, 4)
(4, 8)


In [41]:
arr2.ravel()
print(arr2)
arr1.ravel()
print(arr1)

# if and only id strides are same then only addition can be done

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [43]:
arr3 = np.arange(1,11)
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.array_split(arr3, 2)
#try vsplit an hsplit

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [50]:
#ufunc
arr4 = np.array =([1,2,3,4,5])
np.add.reduce(arr4)

np.int64(15)

In [51]:
np.add.accumulate(arr4)

array([ 1,  3,  6, 10, 15])

In [ ]:

# we can only use axes to normalize IF there has been a Vector or Scalar operation

In [53]:
#numpy is a libaray written in c so its faster than python
#Numba: -> to optimize custom function (parallel running)


In [60]:
# custom func
def add(a,b)->np.int32:
    return a+b
#add-> func name, 2->no. parameters,1 -> np. o/p parameter

my_add = np.frompyfunc(add, 2, 1,)
#my_add.reduce(arr2, arr3)


In [61]:
#np.vectorization[add](arr1, arr2)


In [62]:
# decorator -> func that take another func as a argument and extends the behavioue of the latter func , without explicity modifying it


In [ ]:
import time
def profiling_decorator(func):
    def inner(*args, **kwargs):
        #before = time.time()

In [ ]:
# wo use numba/numpy to compine the processors og cpu and gpu